# Generated by Django 3.2.3 on 2021-05-30 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0001_initial'),
        ('diario', '0002_alter_diario_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diario',
            name='comidas',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3')], default=2, max_length=1),
        ),
        migrations.AlterField(
            model_name='diario',
            name='total_cal',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterUniqueTogether(
            name='diario',
            unique_together={('fecha', 'mascota')},
        ),
    ]
