# Generated by Django 3.2.3 on 2021-06-10 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0005_alter_diario_total_cal'),
    ]

    operations = [
        migrations.AddField(
            model_name='diario',
            name='completado',
            field=models.BooleanField(default=False),
        ),
    ]
