# Generated by Django 3.2.3 on 2021-06-10 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0006_diario_completado'),
    ]

    operations = [
        migrations.AddField(
            model_name='diario',
            name='dif_cal',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
