# Generated by Django 3.2.3 on 2021-05-30 00:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('tipo', models.CharField(choices=[('Gato', 'Gato'), ('Perro', 'Perro')], max_length=5)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=4)),
                ('edad', models.PositiveIntegerField(default=12, help_text='Edad en meses')),
                ('actividad', models.CharField(choices=[('Poca', 'Poca'), ('Normal', 'Normal'), ('Moderada', 'Moderada'), ('Intensa', 'Intensa')], default='Poca', max_length=10)),
                ('meta', models.PositiveIntegerField(default=0, verbose_name='Meta calorias')),
                ('tamaño', models.CharField(choices=[('Muy pequeño', 'Muy pequeño'), ('Pequeño', 'Pequeño'), ('Mediano', 'Mediano'), ('Grande', 'Grande'), ('Gigante', 'Gigante')], default='Mediano', max_length=15)),
                ('esterilizado', models.BooleanField(default=False, help_text='Tildado = Si')),
                ('objetivo', models.CharField(choices=[('Bajar peso', 'Bajar peso'), ('Mantener peso', 'Mantener peso'), ('Aumentar peso', 'Aumentar peso')], default='Mantener peso', max_length=15)),
                ('dueño', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
