# Generated by Django 3.2.3 on 2021-06-25 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0002_alter_mascota_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='meta',
            field=models.PositiveIntegerField(blank=True, verbose_name='Meta calorias'),
        ),
    ]
