# Generated by Django 3.2.3 on 2021-06-25 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0003_alter_mascota_meta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='meta',
            field=models.PositiveIntegerField(null=True, verbose_name='Meta calorias'),
        ),
    ]
