# Generated by Django 3.2.3 on 2021-08-23 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0005_alter_mascota_peso'),
    ]

    operations = [
        migrations.CreateModel(
            name='PesoMascotaDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.DecimalField(decimal_places=2, help_text='Peso en Kg', max_digits=4)),
                ('fecha', models.DateField()),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mascotas.mascota')),
            ],
            options={
                'ordering': ['id', 'fecha'],
            },
        ),
    ]
