# Generated by Django 3.2.3 on 2021-08-23 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0006_pesomascotadiario'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pesomascotadiario',
            unique_together={('mascota', 'fecha')},
        ),
    ]
