# Generated by Django 3.2.3 on 2021-09-10 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0007_alter_pesomascotadiario_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='Imgmascotas', verbose_name='Imagen'),
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('importancia', models.CharField(choices=[('Normal', 'Normal'), ('Moderada', 'Moderada'), ('Alta', 'Alta')], max_length=8)),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mascotas.mascota')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
