# Generated by Django 3.2.3 on 2021-09-10 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0008_auto_20210910_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='Imgmascotas/', verbose_name='Imagen'),
        ),
    ]
