# Generated by Django 3.2.3 on 2021-09-10 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0009_alter_mascota_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='texto',
            field=models.CharField(default='Nota', max_length=200),
        ),
    ]
