# Generated by Django 3.2.3 on 2021-09-16 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0010_nota_texto'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='archivado',
            field=models.BooleanField(default=False),
        ),
    ]
