# Generated by Django 3.2.3 on 2021-05-30 00:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('diario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=70)),
                ('calorias', models.PositiveIntegerField(help_text='por kg')),
                ('creada_el', models.DateField(auto_now_add=True)),
                ('creada_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AlimentoConsumido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('porcion', models.CharField(choices=[('1g', '1 gramo'), ('100g', '100 gramos')], default='1g', max_length=10)),
                ('total_cal', models.PositiveIntegerField()),
                ('alimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alimentos.alimento')),
            ],
        ),
        migrations.CreateModel(
            name='Comida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Comida', max_length=25)),
                ('alimento_consumido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alimentos.alimentoconsumido')),
                ('fecha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diario.diario')),
            ],
        ),
    ]
