# Generated by Django 3.2.3 on 2021-05-30 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alimentos', '0003_alter_comida_diario_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comida',
        ),
    ]
