# Generated by Django 3.2.3 on 2021-05-30 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0002_alter_diario_id'),
        ('alimentos', '0004_delete_comida'),
    ]

    operations = [
        migrations.AddField(
            model_name='alimentoconsumido',
            name='diario',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='diario.diario'),
            preserve_default=False,
        ),
    ]
