# Generated by Django 3.2.3 on 2021-06-01 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alimentos', '0005_alimentoconsumido_diario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alimentoconsumido',
            name='porcion',
            field=models.CharField(choices=[('1g', '1'), ('100g', '100')], default='1g', max_length=10),
        ),
    ]
