# Generated by Django 3.2.3 on 2021-06-01 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alimentos', '0006_alter_alimentoconsumido_porcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alimentoconsumido',
            name='porcion',
            field=models.CharField(choices=[('1g', '1'), ('100g', '100')], default='1g', help_text='gramos', max_length=10),
        ),
    ]
