# Generated by Django 3.2.3 on 2021-06-01 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alimentos', '0007_alter_alimentoconsumido_porcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alimentoconsumido',
            name='porcion',
            field=models.CharField(choices=[('1', '1'), ('100', '100')], default='1g', help_text='Gramos', max_length=10),
        ),
    ]
