# Generated by Django 3.2.3 on 2021-09-08 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alimentos', '0008_alter_alimentoconsumido_porcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alimentoconsumido',
            name='porcion',
        ),
    ]
